Repository fireflies-crew/hello-api, pull requests merged in 2021-04, with the labels that each got.

#8 docs: add deployment steps readme
  Readme.md
Labels: VM

#22 add some security features
  .gitignore
  terraform/keyvault.tf
  terraform/main.tf
  terraform/resourcegroup.tf
  terraform/tests/unit/unit_test.go
  terraform/vm_server.tf
  terraform/vnet.tf
Labels: VM

#30 ci: Adds SQL server/db for geo replication across 2 regions
  .gitignore
  terraform/sql.tf
  terraform/terraform.tfvars.sample
  terraform/tests/unit/unit_test.go
  terraform/variables.tf
Labels: Database, HA/DR

#1 Add datadog eventing
  HelloApi/HelloApi.Tests/App.config
  HelloApi/HelloApi.Tests/Controllers/HomeControllerTest.cs
  HelloApi/HelloApi.Tests/HelloApi.Tests.csproj
  HelloApi/HelloApi.Tests/packages.config
  HelloApi/HelloApi/App_Start/FilterConfig.cs
  HelloApi/HelloApi/App_Start/UnityConfig.cs
  HelloApi/HelloApi/App_Start/UnityMvcActivator.cs
  HelloApi/HelloApi/App_Start/WebApiConfig.cs
  HelloApi/HelloApi/Controllers/HomeController.cs
  HelloApi/HelloApi/Controllers/ValuesController.cs
  HelloApi/HelloApi/Filters/LogFilter.cs
  HelloApi/HelloApi/HelloApi.csproj
  HelloApi/HelloApi/Loggers/DataDogStatsdEventLogger.cs
  HelloApi/HelloApi/Loggers/IEventLogger.cs
  HelloApi/HelloApi/Web.config
  HelloApi/HelloApi/packages.config
Labels: Observability

#33 feat: Adds simple SQL project
  Database/Database.sln
  Database/Sql/Sql.sqlproj
  Database/Sql/dbo.Category.sql
  Database/Sql/dbo.FK_Product_Category_Category.sql
  Database/Sql/dbo.FK_Product_Category_Product.sql
  Database/Sql/dbo.Product.sql
  Database/Sql/dbo.Product_Category_Rel.sql
Labels: Database

#39 fix: Fixes naming convention for sql to avoid conflicts
  terraform/keyvault.tf
  terraform/sql.tf
  terraform/tests/unit/unit_test.go
Labels: Database
